name: PluginManager
main: com.gmail.bobason01.PluginManager
version: 1.0-SNAPSHOT
api-version: 1.19
author: crston
commands:
  pluginmanager:
    aliases: [pm]
    permission: pluginmanager.use
    usage: /pluginmanager <enable|disable|reload|list> [plugin]
permissions:
  pluginmanager.use:
    default: op