name: PluginManager
main: com.gmail.bobason01.PluginManager
version: 5.0
api-version: 1.13
author: crston
commands:
  pluginmanager:
    aliases: [pm]
    permission: pluginmanager.use
    usage: /pluginmanager < enable | disable | reload | unload | load | confirm | list > [plugin]
permissions:
  pluginmanager.use:
    default: op